server:
 port: 8080
 error:
  include-binding-errors: always
  include-message: always
  include-stacktrace: never
  
spring:
 main:
  allow-circular-references: true
 datasource:
  url: jdbc:postgresql://localhost:5432/greenRent_db
  username: postgres
  password: password
  driver-class-name: org.postgresql.Driver
 jpa:
  hibernate: 
   ddl-auto: update
  show-sql: true
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  properties:
   '[hibernate.format_sql]': true  
   
logging:
 file:
  name: log/greenrent.log
 pattern:
  file: "%d %-5level [%thread] %logger:%msg%n"
 level:
  '[org.springframework.web]' : WARN
  '[org.hibernate]' : INFO
  '[org.visionrent]' : DEBUG
greenrent:
 app:
   jwtSecret: mySecretKey
   jwtExpirationMs: 86400000